// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByLc2KmQPEVnEZCAYKvuiJLMoMdXDEaVY',
    appId: '1:633502861426:web:9ed064c416ab11cc5e1aeb',
    messagingSenderId: '633502861426',
    projectId: 'chatapplication-47c1e',
    authDomain: 'chatapplication-47c1e.firebaseapp.com',
    storageBucket: 'chatapplication-47c1e.appspot.com',
    measurementId: 'G-D0KGQ5RXP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAskTjoBtKe7y8533r2QcQc8MHqCmQpq-E',
    appId: '1:633502861426:android:4e5cf9d6f5fa8fb25e1aeb',
    messagingSenderId: '633502861426',
    projectId: 'chatapplication-47c1e',
    storageBucket: 'chatapplication-47c1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQXFVScU45K3SIBVUzeG8zgmLcd6gfza4',
    appId: '1:633502861426:ios:d12d0d5c2b780e0c5e1aeb',
    messagingSenderId: '633502861426',
    projectId: 'chatapplication-47c1e',
    storageBucket: 'chatapplication-47c1e.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
